version: '3.8'
services:
  server:
    image: node:20-alpine
    working_dir: /workspace/server
    command: sh -c "npm install -w server && npm run dev -w server"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/workspace

  client:
    image: node:20-alpine
    working_dir: /workspace/client
    command: sh -c "npm install -w client && npm run dev -w client"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/workspace
